# Where things are
source:       .
destination:  ./_site
#plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: 9leg
description: java,scala
keywords: java,scala
url: https://jiadreamran.github.io/my_blog
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: Front Page
    url: /index.html
  - text: Categories 
    url: /categories.html
  - text: Archives
    url: /archives.html
  - text: About
    url: /about.html
  - text: Links
    url: /links.html

#Author config
author:
    name: jiadreamran
    email: jiadreamran@gmail.com
    imageLink: /images/header.jpg
    simpleIntro: Windows programmer trying to get adapted to the world
    detailIntro:
      <p>Developer working for reinsurance industry</p>
      <p>Try to become ahead of my work</p>
      <p>Java, JavaScript, Python, and other languages coming...</p>
      <p></p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/
  - class: icon-facebook
    url: http://facebook.com/
  - class: icon-github-alt
    url: https://github.com/zJiaJun/
  - class: icon-twitter
    url: https://twitter.com/zhujiajun_me
  - class: icon-google-plus
    url: https://plus.google.com/116595571760191938657/about

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends    
  - item:
    - text: Java Code Geeks
      url: http://www.javacodegeeks.com/
    - text: Web Developer
      url: http://www.fromdev.com/
    - text: BeginnersBook
      url: http://beginnersbook.com/
    - text: Mkyong
      url: http://www.mkyong.com/
    - text: Java By Nataraj
      url: http://javabynataraj.blogspot.in/
    message: About Java

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: 

#baidu tongji
baiduTongji:
  config: false
  id: 

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: false
  id: 9leg

#baidu share config
baiduShare:
  config: false
  